### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by bismark** [ckruse/microformats2-elixir#1]
Hi, I've recently joined the IndieWeb world and I would like to start seeing more Elixir-based IndieWeb projects.

Unfortunately AGPL is a very restrictive license for a library, especially for use in personal projects.

Would you be open to relicensing this project with a more liberal license? The [Elixir Library Guidelines](https://hexdocs.pm/elixir/master/library-guidelines.html#publishing) recommend MIT or Apache 2.0.

**Comment by ckruse** [comment]
I relicenced it to MIT
