### ISSUE TITLE
Revise the `elixir: "~> 1.6"` requirement

### ISSUE THREAD

**Issue by NobbZ** [ckruse/microformats2-elixir#14]
Currently the `mix.exs` specifies that elixir of 1.6 or newer is required, though when one uses elixir 1.6 there will be warnings when compiling the dependencies, that `:earmark` and `:ex_doc` require at least elixir 1.7.

This might not be relevant for production though, as `:ex_doc` and therefore `:earmark` are `:dev`-only dependencies.

Tests seem to pass with elixir 1.6.6 though.

Using some sort of CI would help to uncover issues like this early.

**Comment by ckruse** [comment]
Thanks! Good hint! I updated the elixir dependency to 1.7
