### ISSUE TITLE
Fails to Parse Page

### ISSUE THREAD

**Issue by jalcine** [ckruse/microformats2-elixir#2]
I'm getting errors when attempting to parse a few pages with content. Not sure why.

https://aaronparecki.com/2018/12/17/7/blocking-domains

**Comment by ckruse** [comment]
Thanks for the report. I published a new version 0.2.1 fixing this bug. Floki returned an empty list instead of nil for a missing attribute. Should work now.

**Comment by jalcine** [comment]
Ah I _just_ produced a patch for it, lol. Next time, I'll just provide said patch.

Nice work with the project!
