### ISSUE TITLE
Switch from httpotion to tesla

### ISSUE THREAD

**Issue by jpcaruana** [ckruse/microformats2-elixir#8]
Hi,

`httpotion` seems to be retired in favor of [tesla](https://github.com/teamon/tesla), it would be great to switch to it, what do you think ?

See below an install of this lib:

```bash
mix deps.get
New:
  floki 0.26.0
  html_entities 0.5.1
  httpotion 3.1.3 RETIRED!
    (deprecated) Not really maintained, please check out Tesla
  ibrowse 4.4.0
  microformats2 0.2.2
```

**Comment by ckruse** [comment]
Oh wow, I didn't expect this.

**Comment by ckruse** [comment]
I published a new version (with some slight modifications), thanks for your contributions!
